### ISSUE TITLE
How about your working at souche?

### ISSUE THREAD

**Issue by oyyd** [XadillaX/ama#1]
Hi @XadillaX.
It seems that you are working at souche and I found that you have done some work for nodejs, libuv and other open source projects. That's really impressive.
And I want to know how you balance your work and your spare time for doning all of these, and also how your apply your experiences of oss to your work?

**Comment by XadillaX** [comment]
My spare time contains gaming (King of Pesticide, PS4, Cities, etc), coding (mainly open-source) and writing (now I'm writing a book about Node.js C++ addons). And if necessary I will do the coding on my working time, e.g. [Toshihiko](https://github.com/xadillax/toshihiko) and [Akyuu.js](https://github.com/akyuujs/akyuu).

The most valuable experiences of oss is the code style and quality.
