### ISSUE TITLE
关于译著的问题请教

### ISSUE THREAD

**Issue by terasum** [XadillaX/ama#14]
大神你好，我最近也在计划做一些感兴趣领域著作的翻译工作，想请问一下，做翻译工作在版权问题，出版问题上是否有一些需要注意的地方呢？

**Comment by XadillaX** [comment]
通常都是跟出版社聊好。版权交给出版社去拿，这边负责翻译就好了。

**Comment by terasum** [comment]
@XadillaX 非常感谢，我尝试联系一下出版社
