### ISSUE TITLE
想了解下 CONF 社区后续准备做什么事情，应该怎么参与一起共建。

### ISSUE THREAD

**Issue by uknowzheng** [XadillaX/ama#16]

**Comment by XadillaX** [comment]
这个目前还在筹备阶段，可以先开始参与到 egg-core 的贡献。

**Comment by uknowzheng** [comment]
> 这个目前还在筹备阶段，可以先开始参与到 egg-core 的贡献。

这个项目和egg会有差异化吗？

**Comment by XadillaX** [comment]
> > 这个目前还在筹备阶段，可以先开始参与到 egg-core 的贡献。
> 
> 这个项目和egg会有差异化吗？

不出意外的话，后续 Egg.js 也是基于 CONF 的。

**Comment by uknowzheng** [comment]
> 

Thx～我可以看看

**Comment by XadillaX** [comment]
现在已经将 CONF 孵化成 Artus.js 了。
