### ISSUE TITLE
关于crc64_ecma182.js，web端file文件，如果文件稍微大一点会报错

### ISSUE THREAD

**Issue by xiang-fish** [XadillaX/ama#20]
crc64.crc64(_buffer)， 如果_buffer是一个10几M的文件会报错：
`Error: Aborted(Cannot enlarge memory arrays to size 18509824 bytes (OOM). Either (1) compile with -sINITIAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -sALLOW_MEMORY_GROWTH which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with -sABORTING_MALLOC=0)
`
你有遇到这个问题吗，怎么处理？

谢谢。。

**Comment by XadillaX** [comment]
分段。

```js
const ret = crc64.crc64(new Buffer("123456789"), "0");
```

`prev` 为上一段计算出来的结果。
