### ISSUE TITLE
any tips for beginners who want to contribute to open source?

### ISSUE THREAD

**Issue by onluiz** [XadillaX/ama#4]
any tips for beginners who want to contribute to open source?
How did you get into the world of open source?

=)

**Comment by XadillaX** [comment]
If there's missing anything, just make it.

For an example, I need CRC64 in Node.js to check [Aliyun OSS files](https://www.alibabacloud.com/help/doc-detail/43394.htm). But there's no CRC64 package for Node.js and I created the package https://github.com/souche-koumakan/crc64_ecma182 and make it open-sourced.

Another example, when I worked for huaban.com, I had a demand to extract the theme color (aka. color palette) for a picture just like [dribbble](https://dribbble.com/shots/3801026-Levels-crop-05) does. I finished the whole work and abstracted the algorithm as a module and make the business unrelated algorithm module open-sourced. Refs: https://github.com/XadillaX/thmclrx and https://github.com/XadillaX/byakuren.

What's more, when I'm using others modules, sometime it will occur bugs. We can figure out some simple bugs by reading the source code and debugging. After resolved, we can make a PR for that project. For an example, long long ago I found that when I'm using multiple primary keys in [Sequelize](https://github.com/sequelize/sequelize), it'll have some problem in `Instance::destroy()`. After reading the code of `destroy()`, I found the cause finally and add some code to fix it: https://github.com/sequelize/sequelize/commit/818f7077d01b6499b21186f1ae2b6c7d378d4932.

For Node.js, you may not only find bug by yourself, but also can find bugs in [Issues](https://github.com/nodejs/node/issues). Read the source code of Node.js, that would be helpful. If you find some issue that you are able to resolve, just do it. And what's more, for Node.js, contributing to the source code is not the only way. You may also contribute to the document (eg. https://github.com/nodejs/node/commit/ca8a29c3606421d71ce3120cd34febacd7874293), tests (eg. https://github.com/nodejs/node/commit/befede64f14858ffea4e8d6f93700be07e0f85fc) and so on.

I think the most important things are keeping reading and just make it if you find out some missing part.

**Comment by onluiz** [comment]
Awesome tips! I had once contributted to a repo (https://github.com/chafey/cornerstoneWebImageLoader/pull/2) that focus on a viewer for radiological images (in JavaScript) and it was just great! I think I will focus on it so. 

Thank you for the tips.
