### ISSUE TITLE
Uh huh... i want be like you , what should i do

### ISSUE THREAD

**Issue by huhu2356** [XadillaX/ama#7]
yeah , that is the dream of my life, but it is too far away. So first let's make a small target ,
~~make a hundred million~~ how to find a node job ?

now , i am graduate from a year , not cs degree , no work , no money , no place to live ,
life is so hard , but you , it's you guide me like a star , drive me to self-study js and node for about two months .

so if i want to find a job and escape from hell , what next should i do , like learn what knowledge about programming ~~or just study building the time machine back to the past~~

**Comment by XadillaX** [comment]
+ Data Structure;
+ Algorithm;
+ Database;
+ C / C++ or Java, etc;
+ Get some achievement;
+ Read the source code of Node.js; *
+ https://www.zhihu.com/lives/907210790807949312

**Comment by fridego** [comment]
another advice： if possible，open your own project and make commits to github every day, like you!

**Comment by PabloLION** [comment]
这广告打得妙呀
