### ISSUE TITLE
关于如何打造家庭影院

### ISSUE THREAD

**Issue by Akira0705** [XadillaX/ama#8]
想知道打造的家庭影院的配置是怎样的呢？

**Comment by XadillaX** [comment]
都是入门级的配置。

+ **激光电视**：[JmGO S2](http://detail.zol.com.cn/Laser_TV/index1238527.shtml)
+ **100 寸抗光幕布**：忘了什么牌子了
+ **家庭影院**：Bose SoundTouch 300 Soundbar + Bose Acoustimass 300 + Bose Vitural Invisible 300 一套
